name: Github Action Boolean Test

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up a conditional variable to env
        run: |
          echo "value=${{ false || 'hoge' }}" >> $GITHUB_ENV
          echo "falseValue=${{ false }}" >> $GITHUB_ENV

      - name: Use the conditional variable from env
        run: |
          echo "${{ env.value }}"
          FALSE_VALUE="${{ env.falseValue }}"
          if [ "${{ env.falseValue }}" ]; then
            echo "falseValue is not false"
          else
            echo "falseValue is false"
          fi

      - name: Set up a conditional variable to output
        id: output_step
        run: |
          FALSE_VALUE=false
          if [ "$FALSE_VALUE" = false ]; then
            echo "falseValue is false"
            echo "falseValue="$FALSE_VALUE" >> $GITHUB_OUTPUT
          else
            echo "falseValue is not false"
          fi

      - name: Use the conditional variable from output
        run: |
          echo "env.value: ${{ env.value }}"
          ENV_VALUE=${{ env.falseValue || true }}
          if [ "$ENV_VALUE" ]; then
            echo "ENV_VALUE is true"
          else
            echo "ENV_VALUE is false"
          fi

          OUTPUT_VALUE=${{ steps.output_step.outputs.falseValue || true }}
          if [ "$OUTPUT_VALUE" ]; then
            echo "OUTPUT_VALUE is true"
          else
            echo "OUTPUT_VALUE is false"
          fi
