name: Github Action Boolean Test

on:
  workflow_dispatch:

jobs:
  echo:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up a conditional variable
        id: example_step
        run: echo "value=${{ false || 'hoge' }}" >> $GITHUB_ENV

      - name: Use the conditional variable
        run: echo "${{ env.value }}"
